"use client"

import {
  motion,
  AnimatePresence,
  useAnimation,
  useMotionValue,
  useTransform,
  useScroll,
  useInView,
  useSpring,
  animate,
  m,
  MotionConfig,
  LayoutGroup,
  useMotionTemplate,
  useReducedMotion,
  useTime,
  useViewportScroll,
  useWillChange,
  stagger,
  type Transition,
  type Variants,
  type AnimationControls,
  type TargetAndTransition,
  type PanInfo,
  type Tween,
  type Spring,
  type Inertia,
  type Keyframes,
  type MotionProps,
  type MotionStyle,
  type MotionValue,
  type MotionAdvancedProps,
  type HTMLMotionProps,
  type SVGMotionProps,
} from "framer-motion"

export {
  motion,
  AnimatePresence,
  useAnimation,
  useMotionValue,
  useTransform,
  useScroll,
  useInView,
  useSpring,
  animate,
  m,
  MotionConfig,
  LayoutGroup,
  useMotionTemplate,
  useReducedMotion,
  useTime,
  useViewportScroll,
  useWillChange,
  stagger,
  type Transition,
  type Variants,
  type AnimationControls,
  type TargetAndTransition,
  type PanInfo,
  type Tween,
  type Spring,
  type Inertia,
  type Keyframes,
  type MotionProps,
  type MotionStyle,
  type MotionValue,
  type MotionAdvancedProps,
  type HTMLMotionProps,
  type SVGMotionProps,
}
